india_real_estate:
  mandatory_intents:
    - possession_delay
    - refund_and_withdrawal
    - interest_and_compensation
    - force_majeure
    - defect_liability
    - alteration_and_change
    - agreement_terms
    - maintenance_and_common_areas
    - governing_law
